#!/usr/bin/env bash

set -e

NODE_NAME=meshmedia

sudo apt-get update -y || true

# Install essential packages
sudo apt-get install git nginx -y

# Install useful tools
sudo apt-get install vim socat oping bmon iperf3 -y

# Configure node name 
sudo echo "${NODE_NAME}" | sudo tee /etc/hostname > /dev/null
sudo sed -i -e "s/raspberrypi/${NODE_NAME}/" /etc/hosts

# Clone repository and install node
git clone https://github.com/hyphacoop/meshmedia.git
cd meshmedia
./install2