#!/usr/bin/env bash

set -e

NODE_NAME=meshmedia

sudo apt-get update -y || true

# Install essential packages
sudo apt-get install git nginx -y

# Install useful tools
sudo apt-get install vim socat oping bmon iperf3 -y

# Configure node name 
sudo echo "${NODE_NAME}" | sudo tee /etc/hostname > /dev/null
sudo sed -i -e "s/raspberrypi/${NODE_NAME}/" /etc/hosts

# Configure access point
source hostapd/install

# Install ipfs
source ipfs/install

# Install player from tomeshnet/ipfs-live-streaming
source player/install

# Reboot node
echo -e "Congratulations! Your meshmedia node is ready at ${NODE_NAME}.local"
echo -e "Connect your computer to the access point with the same name and visit http://10.0.0.1"
sudo reboot